<?php

namespace App\Http\Requests\Catalog;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize():bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules():array
    {
        return [
            'title' => ['required', 'string', 'min:5', 'max:150'],
            'description' => ['required', 'string', 'min:5'],
            'isImage' => ['nullable', 'boolean'],
            'sourceImage' => ['nullable', 'file', 'image', 'nimes:jpg,png']
        ];
    }

    public function messages()
{
    return [
      'required' => 'Неверно заполнено поле :attribute'
    ];
}
public function attributes()
{
    return parent::attributes(); // TODO: Change the autogenerated stub
}
}
